version: '3'

services:

  api:
    container_name: api
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.production
    ports:
      - "6000:8080"
    networks:
      - api_network
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
    networks:
      - db_network
      - api_network
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - db_network

volumes:
  postgres:

networks:
  db_network:
  api_network: