// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CitiesColumns holds the columns for the "cities" table.
	CitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "id_tara", Type: field.TypeInt},
		{Name: "nume_oras", Type: field.TypeString, Unique: true},
		{Name: "latitudine", Type: field.TypeFloat64},
		{Name: "longitudine", Type: field.TypeFloat64},
	}
	// CitiesTable holds the schema information for the "cities" table.
	CitiesTable = &schema.Table{
		Name:       "cities",
		Columns:    CitiesColumns,
		PrimaryKey: []*schema.Column{CitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cities_countries_Cities",
				Columns:    []*schema.Column{CitiesColumns[1]},
				RefColumns: []*schema.Column{CountriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CountriesColumns holds the columns for the "countries" table.
	CountriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nume_tara", Type: field.TypeString, Unique: true},
		{Name: "latitudine", Type: field.TypeFloat64},
		{Name: "longitudine", Type: field.TypeFloat64},
	}
	// CountriesTable holds the schema information for the "countries" table.
	CountriesTable = &schema.Table{
		Name:       "countries",
		Columns:    CountriesColumns,
		PrimaryKey: []*schema.Column{CountriesColumns[0]},
	}
	// TemperaturesColumns holds the columns for the "temperatures" table.
	TemperaturesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "id_oras", Type: field.TypeInt},
		{Name: "valoare", Type: field.TypeFloat64},
		{Name: "timestamp", Type: field.TypeTime},
	}
	// TemperaturesTable holds the schema information for the "temperatures" table.
	TemperaturesTable = &schema.Table{
		Name:       "temperatures",
		Columns:    TemperaturesColumns,
		PrimaryKey: []*schema.Column{TemperaturesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "temperatures_cities_Temperatures",
				Columns:    []*schema.Column{TemperaturesColumns[1]},
				RefColumns: []*schema.Column{CitiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CitiesTable,
		CountriesTable,
		TemperaturesTable,
	}
)

func init() {
	CitiesTable.ForeignKeys[0].RefTable = CountriesTable
	TemperaturesTable.ForeignKeys[0].RefTable = CitiesTable
}
