// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"tema-sprc-go/ent/city"
	"tema-sprc-go/ent/temperature"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CityCreate is the builder for creating a City entity.
type CityCreate struct {
	config
	mutation *CityMutation
	hooks    []Hook
}

// SetIDTara sets the "id_tara" field.
func (cc *CityCreate) SetIDTara(i int) *CityCreate {
	cc.mutation.SetIDTara(i)
	return cc
}

// SetNumeOras sets the "Nume_oras" field.
func (cc *CityCreate) SetNumeOras(s string) *CityCreate {
	cc.mutation.SetNumeOras(s)
	return cc
}

// SetLatitudine sets the "Latitudine" field.
func (cc *CityCreate) SetLatitudine(f float64) *CityCreate {
	cc.mutation.SetLatitudine(f)
	return cc
}

// SetLongitudine sets the "Longitudine" field.
func (cc *CityCreate) SetLongitudine(f float64) *CityCreate {
	cc.mutation.SetLongitudine(f)
	return cc
}

// AddTemperatureIDs adds the "Temperatures" edge to the Temperature entity by IDs.
func (cc *CityCreate) AddTemperatureIDs(ids ...int) *CityCreate {
	cc.mutation.AddTemperatureIDs(ids...)
	return cc
}

// AddTemperatures adds the "Temperatures" edges to the Temperature entity.
func (cc *CityCreate) AddTemperatures(t ...*Temperature) *CityCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cc.AddTemperatureIDs(ids...)
}

// Mutation returns the CityMutation object of the builder.
func (cc *CityCreate) Mutation() *CityMutation {
	return cc.mutation
}

// Save creates the City in the database.
func (cc *CityCreate) Save(ctx context.Context) (*City, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CityCreate) SaveX(ctx context.Context) *City {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CityCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CityCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CityCreate) check() error {
	if _, ok := cc.mutation.IDTara(); !ok {
		return &ValidationError{Name: "id_tara", err: errors.New(`ent: missing required field "City.id_tara"`)}
	}
	if _, ok := cc.mutation.NumeOras(); !ok {
		return &ValidationError{Name: "Nume_oras", err: errors.New(`ent: missing required field "City.Nume_oras"`)}
	}
	if _, ok := cc.mutation.Latitudine(); !ok {
		return &ValidationError{Name: "Latitudine", err: errors.New(`ent: missing required field "City.Latitudine"`)}
	}
	if _, ok := cc.mutation.Longitudine(); !ok {
		return &ValidationError{Name: "Longitudine", err: errors.New(`ent: missing required field "City.Longitudine"`)}
	}
	return nil
}

func (cc *CityCreate) sqlSave(ctx context.Context) (*City, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CityCreate) createSpec() (*City, *sqlgraph.CreateSpec) {
	var (
		_node = &City{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(city.Table, sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.IDTara(); ok {
		_spec.SetField(city.FieldIDTara, field.TypeInt, value)
		_node.IDTara = value
	}
	if value, ok := cc.mutation.NumeOras(); ok {
		_spec.SetField(city.FieldNumeOras, field.TypeString, value)
		_node.NumeOras = value
	}
	if value, ok := cc.mutation.Latitudine(); ok {
		_spec.SetField(city.FieldLatitudine, field.TypeFloat64, value)
		_node.Latitudine = value
	}
	if value, ok := cc.mutation.Longitudine(); ok {
		_spec.SetField(city.FieldLongitudine, field.TypeFloat64, value)
		_node.Longitudine = value
	}
	if nodes := cc.mutation.TemperaturesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.TemperaturesTable,
			Columns: []string{city.TemperaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(temperature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CityCreateBulk is the builder for creating many City entities in bulk.
type CityCreateBulk struct {
	config
	err      error
	builders []*CityCreate
}

// Save creates the City entities in the database.
func (ccb *CityCreateBulk) Save(ctx context.Context) ([]*City, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*City, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CityCreateBulk) SaveX(ctx context.Context) []*City {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CityCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CityCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
