// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"tema-sprc-go/ent/city"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// City is the model entity for the City schema.
type City struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IDTara holds the value of the "id_tara" field.
	IDTara int `json:"id_tara,omitempty"`
	// NumeOras holds the value of the "Nume_oras" field.
	NumeOras string `json:"Nume_oras,omitempty"`
	// Latitudine holds the value of the "Latitudine" field.
	Latitudine float64 `json:"Latitudine,omitempty"`
	// Longitudine holds the value of the "Longitudine" field.
	Longitudine float64 `json:"Longitudine,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CityQuery when eager-loading is set.
	Edges        CityEdges `json:"edges"`
	id_tara      *int
	selectValues sql.SelectValues
}

// CityEdges holds the relations/edges for other nodes in the graph.
type CityEdges struct {
	// Temperatures holds the value of the Temperatures edge.
	Temperatures []*Temperature `json:"Temperatures,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TemperaturesOrErr returns the Temperatures value or an error if the edge
// was not loaded in eager-loading.
func (e CityEdges) TemperaturesOrErr() ([]*Temperature, error) {
	if e.loadedTypes[0] {
		return e.Temperatures, nil
	}
	return nil, &NotLoadedError{edge: "Temperatures"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*City) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case city.FieldLatitudine, city.FieldLongitudine:
			values[i] = new(sql.NullFloat64)
		case city.FieldID, city.FieldIDTara:
			values[i] = new(sql.NullInt64)
		case city.FieldNumeOras:
			values[i] = new(sql.NullString)
		case city.ForeignKeys[0]: // id_tara
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the City fields.
func (c *City) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case city.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case city.FieldIDTara:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id_tara", values[i])
			} else if value.Valid {
				c.IDTara = int(value.Int64)
			}
		case city.FieldNumeOras:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Nume_oras", values[i])
			} else if value.Valid {
				c.NumeOras = value.String
			}
		case city.FieldLatitudine:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field Latitudine", values[i])
			} else if value.Valid {
				c.Latitudine = value.Float64
			}
		case city.FieldLongitudine:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field Longitudine", values[i])
			} else if value.Valid {
				c.Longitudine = value.Float64
			}
		case city.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field id_tara", value)
			} else if value.Valid {
				c.id_tara = new(int)
				*c.id_tara = int(value.Int64)
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the City.
// This includes values selected through modifiers, order, etc.
func (c *City) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryTemperatures queries the "Temperatures" edge of the City entity.
func (c *City) QueryTemperatures() *TemperatureQuery {
	return NewCityClient(c.config).QueryTemperatures(c)
}

// Update returns a builder for updating this City.
// Note that you need to call City.Unwrap() before calling this method if this City
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *City) Update() *CityUpdateOne {
	return NewCityClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the City entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *City) Unwrap() *City {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: City is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *City) String() string {
	var builder strings.Builder
	builder.WriteString("City(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("id_tara=")
	builder.WriteString(fmt.Sprintf("%v", c.IDTara))
	builder.WriteString(", ")
	builder.WriteString("Nume_oras=")
	builder.WriteString(c.NumeOras)
	builder.WriteString(", ")
	builder.WriteString("Latitudine=")
	builder.WriteString(fmt.Sprintf("%v", c.Latitudine))
	builder.WriteString(", ")
	builder.WriteString("Longitudine=")
	builder.WriteString(fmt.Sprintf("%v", c.Longitudine))
	builder.WriteByte(')')
	return builder.String()
}

// Cities is a parsable slice of City.
type Cities []*City
