// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// City is the predicate function for city builders.
type City func(*sql.Selector)

// Country is the predicate function for country builders.
type Country func(*sql.Selector)

// Temperature is the predicate function for temperature builders.
type Temperature func(*sql.Selector)
